### ISSUE TITLE
Error en estimateOrderPrice

### ISSUE THREAD

**Issue by connaxisltatarin** [vmari/glovo-api-php#1]
Hola buenas! Tienen idea si el plugin sigue funcionando? Lo baje para hacer algunas pruebas y no me funciona. Un cambio que detecte al parecer desde el lado de glovo es que el parámetro de longitud ahora lo llaman **lon** en lugar de **lng**, asi que hice ese pequeño cambio localmente y ahora realiza la llamada para estimar el precio del envío pero siempre recibo el mensaje de error sin mucho mas detalle.

**Comment by vmari** [comment]
Hola! El parametro lon se envía correctamente en el parseo, solo se utiliza otro nombre en la entidad, por lo tanto dudo que sea eso. Verificá los pasos del README. Es necesario tener una tarjeta asociada a la cuenta de Glovo. Ahora lo verifique con mis keys y está funcionando.

Te recomiendo que utilices el entorno de producción ya que staging no está funcionando, nunca pude asociar una tarjeta y me fallaron todos los pedidos.

**Comment by connaxisltatarin** [comment]
Correcto! Como vos decís el entorno de staging no funciona era ese el problema, pero el de producción si. Te hago una consulta mas, sabes como hacer pruebas sin asociar una tarjeta? O como hacer para probar sin que se cobre? Gracias.

**Comment by vmari** [comment]
Las requests que hagas sin tarjeta asociada van a fallar, sin avisar por qué. Siempre que el pedido no haya sido aceptado, podes cancelarlo y se te reintegra el monto. Una vez aceptado ya no es posible cancelarlo sin llamar a soporte.
